guardian/itunes-rss

- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- app/controllers/Application.scala
- test/com/gu/ItunesRssItemSpec.scala
- test/resources/itunes-capi-response.json
1. Changed the `guid` field to match the R2 implementation:
* old content served from `http(s)://static(-secure).guim.co.uk/{...}` will have the `guid` field se to `http://download.guardian.co.uk/{...}` for legacy reasons (to match the R2 implementation);
* new content served from `https://audio.guim.co.uk` will preserve its structure
2. Regardless, the actual download url remains `static.guim.co.uk` since using `download.guardian.co.uk` is deprecated [1]
3. The number of podcasts per feed has been bumped up to 5 for testing purposes.
[1] source: Stephen Goldthorpe via email
> Changhe the guid to match r2 implementation

- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/ItunesRssFeedSpec.scala
- test/com/gu/ItunesRssItemSpec.scala
- test/resources/itunes-capi-response.json
> The <itunes:explicit> tag indicates whether your podcast contains explicit material. You can specify the following values:
>   - Yes | Explicit | True.
>
If you specify yes, explicit, or true, indicating the presence of explicit content, the iTunes Store displays an Explicit parental advisory graphic for your podcast.
>   -  Clean | No | False.
>
If you specify clean, no, or false, indicating that none of your podcast episodes contain explicit language or adult content, the iTunes Store displays a Clean parental advisory graphic for your podcast.
> Fix explicit to be no rather than empty

- app/com/gu/itunes/Redirection.scala
- app/controllers/Application.scala
We have the following problem:
- Editors have 2 tags [Film weekly](https://www.theguardian.com/film/series/filmweekly) and [The dailies podcast](https://www.theguardian.com/film/series/the-dailies-podcast) (The first is the old one and the second the new one). All new episodes will have soon only `the dailies podcast` only.
- The guardian has to use `site manager` and not `podcasts connect`. The last one [allows to update your itunes feed](https://help.apple.com/itc/podcasts_connect/#/itca489031e0) but not the first one, so we can't update the feed url on the itunes system. 
Therefore we do only a `301` from the old podcast xml to the new one. This response updates the iTunes Store with the new feed URL and subscribers continue to receive new episodes automatically.
@na7hangood
> Add redirection logic to keep audience of an existing podcast channel

- app/com/gu/itunes/CustomCapiClient.scala
Thrift was [disabled previously](https://github.com/guardian/itunes-rss/pull/21) because concierge [had not been updated](https://github.com/guardian/content-api/pull/1538)
> Use thrift !

- app/com/gu/itunes/Redirection.scala
Similar to the [film weekly to the daily podcast redirection](https://github.com/guardian/itunes-rss/pull/19) we had another redirection from `techweekly` to `chips-with-everything`.
> Add another redirection to keep audience of an existing podcast channel

- app/controllers/Application.scala
From local debugging with `charles`, it looks like apple does not follow relative location redirect.
> Use absolute URL in redirection according to spec

- cloudformation.json
- content-api-itunes-rss.conf
Also switch to t2.micro and increase heap size
Autoscaling is deliberately over-sensitive, triggering on > 10% CPU for 1 minute and quickly scaling up to 20 instances. This is to handle rare but huge spikes of traffic from Apple.
We'll have to wait until the next time Apple decides to DoS us to see if this scaling is sufficient.
> Enable autoscaling

- app/com/gu/itunes/iTunesRssFeed.scala
Reference: https://help.apple.com/itc/podcasts_connect/#/itca489031e0
For now it is only for a single podcast series. @mchv 
The new feed looks like:
```
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">
<channel>
<itunes:new-feed-url>
https://www.theguardian.com/commentisfree/series/what-would-a-feminist-do
</itunes:new-feed-url>
<title>What would a feminist do?</title>
<link>
https://www.theguardian.com/commentisfree/series/what-would-a-feminist-do
</link>
...
```
> Use new-feed field to force Apple to https

- app/com/gu/itunes/Redirection.scala
- app/com/gu/itunes/iTunesRssFeed.scala
This PR builds on work previously done by Mariot to provide a way to change a podcast RSS feed url, migrating the users in the process.
The official documentation is here: https://help.apple.com/itc/podcasts_connect/#/itca489031e0
The two main steps are:
> 1. Set your web server to return an HTTP 301 redirect response when it receives a request for the old feed.
> 2. Use the `<itunes:new-feed-url>` tag in your new feed to point to the new URL.
Changes specifically to this PR are:
1. Code refactor to make it trivial to do this in the future => just add your new redirect in the `redirectsMapping` `Map()`
2. Add a new redirect for `politics-for-humans podcast`
3. Consistently use the `new-feed-url` tag for old podcasts that have been migrated (we were doing the redirect step only)
To expand …
> Provide a consistent way to migrate RSS feed url

- app/com/gu/itunes/Redirection.scala
- app/com/gu/itunes/iTunesRssFeed.scala
Add a `new-feed-url` tag to all our podcasts to tell Apple to use https. Once all theirs system are updated we can revert https://github.com/guardian/fastly-edge-cache/pull/656
@mchv
> Update all feeds to https

- app/com/gu/itunes/iTunesRssItem.scala
Extend Acast proxy to more podcasts. CC @guardian/commercial-dev
> add acast proxy to more podcasts

- app/com/gu/itunes/iTunesRssItem.scala
Adds back the early trial podcasts to use acast proxy (previously added in #39). CC @mchv
> add back trial podcasts to acast proxy

- app/controllers/Application.scala
- project/plugins.sbt
`absoluteURL` has `secure` parameter that need to be set to `true` for redirecting to an `https` location, see [scaladoc](https://www.playframework.com/documentation/2.5.x/api/scala/index.html#play.api.mvc.Call).
This is currently preventing #43 to work properly
I added an upgrade to the latest `2.4.x` play release, before migrating to `2.5.11`
> Fix redirection by using https url

- app/com/gu/itunes/iTunesRssFeed.scala
Debugging #43 it seems that space and carriage returns break the `itunes:new-feed-url` feature :/
> iTunes does not seems to like space and carriage return in the XML

- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/AcastProxySpec.scala
- test/com/gu/ItunesTestData.scala
- test/resources/itunes-capi-response-acast-test.json
Adds new series' to the Acast proxy whitelist and refactors code.
CC @mchv @guardian/commercial-dev
> Roll-out acast to next group of podcasts

- conf/riff-raff.yaml
This should avoid `riff-raff` trying to do the deployment at the same time.
> Add AMI update as a dependency

- app/com/gu/itunes/iTunesRssItem.scala
1. Align the Politics Weekly message with the TIF one
2. Wrap the `itunes:summary` content in the CDATA section, so that we can
3. Embed an HTML link into the summary, so that clients like Overcast interpret it correctly
> A few updates to the RSS summary

- cloudformation.yaml
For some reason, sbt will generate an artefact with a suffix like `-<version>-SNAPSOT` in the name. We've noticed that because the last merge failed to update in PROD. After looking into the S3 folder with riff-raff artefacts, we noticed the presence of two files:
- one with `0.1-SNAPSHOT` from last December
- one with `0.1.0-SNAPSHOT` from today
of course the cloudformation launch config uses the former.
It would probably be best to leave the version name out completely...
> Error in artefact name

- app/com/gu/itunes/iTunesRssItem.scala
Adds a few more ctas to other podcasts and overrides the existing ones for future episodes.
_nb_: there is no expiry date, as the pages will still be up after the campaign
> Add CTAs for the moment

- app/com/gu/itunes/iTunesRssItem.scala
The usage of `gu.com` should be avoided as it slow down access to content for user due to an additional network redirection.
**Background**
We introduced `gu.com` domain for short urls when social networks where including `url` in character counts and therefore it was extremely useful have shorter possible urls. This is no more case, but `gu.com` remains useful on print where number of chars can be very limited.  
**Technical impact of using `gu.com`**
When accessing a `gu.com/bookspod` URL the following connections happen:
- connection to `gu.com/bookspod` redirected to `www.theguardian.com/bookspod`
- connection to `www.theguardian.com/bookspod` redirected  to `support.theguardian.com/contribute?...`
- connection to `support.theguardian.com/contribute?...` redirected to …
> Remove usage of deprecated gu.com domain

- app/controllers/Application.scala
I _think_ this is all that's needed to fetch up to 200 podcasts in a single bound
> Increase number of podcasts requested from 100 to 200

- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/ItunesRssItemSpec.scala
This is added for `SEO` purpose and can be safely removed in RSS
```xml
<item>
<title>
From bootcamp to burnout: how to make it as a YouTuber – podcast
</title>
<description>
Young stars on the Google-owned site can become multi-millionaires almost overnight but controversy has stalked every stage of YouTube’s growth. Plus: Amelia Abraham on rising LGBT hate crimes. Help support our independent journalism at <a href="https://www.theguardian.com/infocus">theguardian.com/infocus</a>
</description>
<enclosure url="https://flex.acast.com/audio.guim.co.uk/2019/06/14-62682-190617_TIF_youtube3.mp3" length="32271338" type="audio/mpeg"/>
<pubDate>Mon, 17 Jun 2019 02:00:06 GMT</pubDate>
<guid>5d0379028f08faa5870543b9</guid>
<itunes:duration>00:26:50</itunes:duration>
<itunes:author>The …
```
> Strip ' – podcast' from title

- app/com/gu/itunes/iTunesRssItem.scala
Following on from https://github.com/guardian/itunes-rss/pull/80, this PR applies a fix to use the correct path for Acast.
> Apply fixed Acast path for the gene gap podcast

- cloudformation.yaml
- conf/riff-raff.yaml
This PR makes some changes to the security configuration of the launch config for the apps auto scale group.
This is to support enabling the Wazuh vulnerability scanner agent. For more details see:
https://github.com/guardian/security-hq/blob/main/hq/markdown/wazuh.md
The changes to the security config are as follows:
- Adding a security group to allow network connections from the agent to the Wazuh service.
- Allowing read permissions on the autoscale group to allow the wazuh agent to collect information about the ASG.
NOTE: In addition to these changes we need to update the AMI configured in the itunes-rss launch configuration to an AMI that has the Wazuh profile:
https://amigo.gutools.co.uk/recipes/ubuntu-bionic-capi
This is configured manually in the stack parameters when deploying …
> Adding cloudformation to support wazuh agent

- cloudformation.yaml
Reconfigure our cloudformation to specify a minimum of two instances. Whilst I was in there I also removed the desired capacity setting as the ASG should always determine that for itself.
Note that the scale-up policy will still double the cluster capacity
```      
ScaleUpPolicy:
AdjustmentType: PercentChangeInCapacity
ScalingAdjustment: '100'
```
and we may choose to rethink that but for now, let's see how it fares.
Upload the new CFN. We only have a PROD env so it'll have to go there. Then run a riff-raff deploy and check that there are two instances running.
If we see fewer autoscaling events (ideally none) and fewer 500 errors logged (ideally none) then that's a success.
Risk should be minimal. We're merely changing the minimum number of running instances, something that the ASG has …
> Set ASG min instances to 2 and remove desired value entirely

- app/com/gu/itunes/iTunesRssItem.scala
Enabling advertising partner Acast for "Comfort Eating" podcast as requested by Max Sanderson
Following instructions in this document:
https://docs.google.com/document/d/1A_6eW_Fc11aRQjiOAQ5iLg38XhJisBuVyqY6U1GdwYY/edit
We will test that the podcasts are available and working with ads.
> Add Comfort Eating podcast configuration

- app/AppComponents.scala
- app/com/gu/itunes/iTunesRssFeed.scala
- app/controllers/Application.scala
- build.sbt
- test/com/gu/ItunesRssFeedSpec.scala
- test/com/gu/ItunesTestData.scala
- test/resources/itunes-capi-response-no-podcast-tag.json
We occasionally see alerts going off for high 5xx rates from the itunes-rss load balancer. On closer inspection it seems that any non-success code (usually 404s) were being returned as 500s.
This PR extends the `Good` `Or` `Bad` model a little by enclosing a `Failed` object in a `Bad` result that contains a message and status code that can be logged properly, and prevent 500s being returned when we're merely being asked for non-existent resources.
A new test is added using an example picked from live logs to check that the expected flavour of `Bad` is generated when the tag doesn't have a podcast field.
We only have a PROD environment for this - so I'm hoping the unit test is sufficient 😬  Once deployed though we can  check manually but expect to see the culprit(s) asking for non-existent …
> Return 404s not 500s when podcasts or tags are not found

- test/com/gu/XmlTestUtils.scala
Avoids conflict with Java 11, which introduces `String::lines`
Resolves a compile error in the tests which prevents this otherwise compatible project from compiling in Java 11.
Java 11 is the most recent Long Term Support Java release.
Play 2.6 claims to need Java 8 OR BETTER; hence we shouldn't need to be explicitly tied to Java 8.
Developers working on this project no longer need to explicitly switch back to Java 8 to work with this code.
Change is to test code only.
If this is incompatible with Java 8 then it should fail hard at the the build stage so should be safe.
> Java 11 compile fix; linesIterator

- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- app/controllers/Application.scala
- conf/routes
Syndication partners can trigger ad free podcasts by identifying themselves using an optional CAPI api key in their requests.
Podcast URLs will accept a user supplied CAPI key on the optional `api-key` query parameter.
ie.
Normal:
```
https://www.theguardian.com/australia-news/series/full-story/podcast.xml
````
Partner:
```
https://www.theguardian.com/australia-news/series/full-story/podcast.xml?api-key=im-a-syndication-partner
```
CAPI api keys are been used as the handle as that's what Content team members most closely associated with Syndication partners access .
If this key is provided we will make and additonal CAPI call to resolve it's user tier.
If the key belongs to the `external` user tier then ads (Acast ads and Membership call outs) will be omitted from the response.
The …
> Ad free podcast responses for partner keys

- app/controllers/Application.scala
Allows a longer tail of old items to be visible to partners who rely on items been present in the feed.
This will increase the size of nearly all existing podcast responses.
Risk that will trigger max response size or time issues with some consumers.
> Increase maximum number of items on podcast response from 200 to 300

- app/controllers/Application.scala
Reverts guardian/itunes-rss#95
> Revert "Increase maximum number of items on podcast response from 200 to 300"

- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/ItunesRssItemSpec.scala
To prevent the been indexed by the likes of Google podcasts.
https://developers.google.com/news/assistant/your-news-update/overview
To prevent the feed from public availability on products like iTunes or Google Podcasts, the value can be set to Yes (not case sensitive). Any other value has no effect.
Do this wrong and we could de index all of our podcasts; hence the test for the normal do not add use case.
> Mark ad free podcasts with with an <itunes:block> tag 

- app/com/gu/itunes/iTunesRssFeed.scala
- test/com/gu/ItunesRssFeedSpec.scala
- test/com/gu/ItunesRssItemSpec.scala
Do not render itunes:new-feed-url for ad free urls. 
We don't want to distract robots which might try to follow this redirection back to the public feeds.
> Ad free feeds do not include the new feed link tag

- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/itunes/ItunesRssItemSpec.scala
Often too long and out of spec which causes the feed to be rejected by consumers who strictly validate it.
Appears not to effect the rendering of Apple of Google Podcast apps.
Safe to remove from syndication feeds. Probably possible to retire from all feeds in the future.
> Omit itunes:subtitle field from ad free podcast feeds.

- test/com/gu/itunes/AcastProxySpec.scala
- test/com/gu/itunes/FilteringSpec.scala
- test/com/gu/itunes/ItunesRssFeedSpec.scala
- test/com/gu/itunes/ItunesTestData.scala
- test/com/gu/itunes/XmlTestUtils.scala
Was probably valid Scala but confused the IDE. 
Java style layout gives a better unboxing in the IDE.
Resolves IDE warnings like this:
> Move test class files to match Java style package folder layout

- app/com/gu/itunes/iTunesRssFeed.scala
- test/com/gu/itunes/ItunesRssFeedSpec.scala
Optional linting but the spec seems fairly clear in this one.
https://validator.w3.org/feed/docs/rss2.html#ltimagegtSubelementOfLtchannelgt
```
(Note, in practice the image <title> and <link> should have the same value as the channel's <title> and <link>.
```
> Validation linting. Channel image link matches channel link.

- app/com/gu/itunes/iTunesRssFeed.scala
- test/com/gu/itunes/ItunesRssFeedSpec.scala
The same as `itunes:image`.
Brings the `<image>` tag inline with Apple's artwork guidelines for ad free feeds.
ie. https://podcasters.apple.com/support/896-artwork-requirements
This is as specific partner request but possibly applicable in general. Applying to ad free initially to keep the review scope smaller.
Apple do not document the usage of the `<image>` tag so it's more differcult to know if this should be applied to the public feeds `<image>` tag.
ie. https://help.apple.com/itc/podcasts_connect/?lang=en#/itcb54353390
Apple talk about the `<itunes:image>` tag. 
Modern iOS and Android podcast clients do not render the small .gif logo from the `<image>`  tag.
> For ad free feeds the channel image is the same large podcast specific image

- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/itunes/ItunesRssItemSpec.scala
- test/resources/itunes-capi-response.json
Rather than the generally longer stand first. 
Limit to 255 characters.
Drop back to an empty (but present) tag if the trailtext is over length. There is already precedent in the code for this approach.
Reacts to w3c feed validation errors. The original specification for itunes:subtitle is lost to history and we can't find an up to date citation other than the w3c feed validator.
The itunes:subtitle does not appear to effect the end user rendering in current versions of Apple and Google podcast apps. This can be checked by examining podcasts from other publishers (like the BBC) who already have unique text in the itunes:subtitle field; it doesn't show in the apps.
> Use the shorter content trailtext to populate the itunes:subtitle tag

- app/controllers/Application.scala
- test/com/gu/itunes/ItunesTestData.scala
- test/resources/itunes-capi-sparse-response.json
Potentially halves the CAPI response size at the cost of additional complexity.
Thrift response size for technology/series/chips-with-everything tag
show all fields: 1048576
show selected fields: 524288
On a local machine curl the output of a podcast tag to a local file.
Apply this change, curl and diff the the files.
The XML should be the same indicating that all of the fields required to render the feed items are still present.
Reduced response size; may lead to less CAPI errors at 1am if less marshalling frees up CAPI resources.
A reduction in average response time for this service's requests would be nice.
Has a field been accidentally omitted in away with subtly changes the feed output.
The composer id been a good example.
> Minimise the number of requested item fields

- app/com/gu/itunes/iTunesRssItem.scala
Adding new Australia Reads podcast
> add australia-reads podcast

- app/com/gu/itunes/iTunesRssItem.scala
Enables the new Australia Reads podcast
> enable au podcast

- app/com/gu/itunes/iTunesRssFeed.scala
- test/com/gu/itunes/ItunesRssFeedSpec.scala
To be the same 3000x300…0 podcast specific image as itunes:image.
While this field is no longer documented in any discoverable Apple documentation this would make our feed consistent with other large podcast publishers are retire an out of date branding usage.
This is the format requested by -large Internet company which is not Apple- and what -large publisher- does in there feeds.
> Migrate generic small logo feed channel image

- app/com/gu/itunes/CustomCapiClient.scala
- app/controllers/Application.scala
- conf/logback.xml
General speculative tinkering without any backing evidence.
Podcasts look like they are been abit demanding with their CAPI requests.
The app is holding long running connections and retrying aggressively.
Reduce the CAPI connection timeout from 20 minutes to 2 seconds.
Podcasts were seen waiting over 10 seconds for a CAPI response during peaks.
This may be preventing us from failing fast and letting the CDN serve a stale cached response.
Additionally we may be blocking other CAPI users by holding our large requests open for long durations.
We are making large expensive requests which take CAPI several seconds to response to during peaks.
To give CAPI a break our pause between retries should be a similar size to the the expected response time.
Because we are making long running requests it …
> Set CAPI connect timeout. Less aggressive retries

- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/itunes/ItunesRssFeedSpec.scala
- test/com/gu/itunes/ItunesRssItemSpec.scala
itunes:block for adfree feeds moves up from item to channel level.
Requested by the syndication partner this effects.
> itunes:block for adfree feeds moves up from item to channel level

- app/com/gu/itunes/iTunesRssItem.scala
Enable the Book It In podcast for Acast pipeline
Check for the presence of a flex wrapper on the URL after this is merged
See above
This is an extension of an existing mechanism and should be risk-free
N/A
> Set up Acast tag for Book It In podcast

- app/com/gu/itunes/iTunesRssItem.scala
Adds the Acast wrapper for this new series tag 
Check that the wrapper is applied correctly after merging
Does the wrapper get applied? If yes, then success!
Very low risk from listener's perspective - the podcast will work with or without the wrapper
N/A
> Set up The Final Word Ashes podcast for Acast

- app/controllers/Application.scala
We have added in the past a hack to return 300 items via pagination but that is using a variable page size which implies that we end up returning overlapping items (first request: page 1, pageSize = 200, returning items 1 to 200, second request: page 2, pageSize = 100, returning items 101 to 200). By keeping the pageSize constant to 100 we resolve this issue.
We retrieve non repeating items for podcasts.
There are no repeated podcasts being returned.
> Fix overlapping returned items by keeping constant page size in requests

- .gitignore
- app/com/gu/itunes/iTunesRssItem.scala
Enable the Weekend podcast for Acast pipeline
Check for the presence of a flex wrapper on the URL after this is merged
See above
This is an extension of an existing mechanism and should be risk-free
N/A
> Added tags for weekend podcast

- app/com/gu/itunes/iTunesRssItem.scala
Enable the Politics Weekly America podcast for Acast pipeline
Check for the presence of a flex wrapper on the URL after this is merged
See above
This is an extension of an existing mechanism and should be risk-free
N/A
> Add tags for Politics Weekly America podcast

- app/com/gu/itunes/iTunesRssItem.scala
Adds a new podcast to the Acast group, and set the launch date to include the trailer episode.
Deploy and check that the trailer has the acast wrapper
If the acast wrapper is applied... SUCCESS!
Risks are minimal. Unless the entire thing fails to build somehow.
N/A
> Add flex tagging for theguardianswomensfootballweekly podcast

- app/controllers/Application.scala
This handles the 401 unauthorized status responses from CAPI.
Why? 
The lack of a 401 handler meant that CAPI 401s where returned as 500s from itunes-rss which was detected in a `fastly-edge-cache` test failure here:
https://github.com/guardian/fastly-edge-cache/blob/cfc6feae4b609d47f466814953553aa4f61479f2/theguardiancom/src/test/scala/com/gu/PodcastIntegrationTest.scala#L20
Run locally and make a request with an invalid api key
> Handle unauthorized status code

- conf/riff-raff.yaml
The `bucket` parameter in riff-raff.yaml has been deprecated in favour of `bucketSsmLookup`.  This causes Riffraff to look up the destination bucket from a parameter in the AWS account's SSM parameter store instead of being hard-coded.  We are currently getting deprecation warnings when deploying this project in riffraff, and merging this PR should fix that by replacing the deprecated parameter with the new one.
> Replace deprecated `bucket` riff-raff parameter

- app/com/gu/itunes/iTunesRssItem.scala
This adds the Acast flex url for the new podcast "ben-roberts-smith-v-the-media"
> Added flextag podcast ben-roberts-smith-v-the-media

- app/com/gu/itunes/iTunesRssItem.scala
This add the flex URL for a new [podcast](https://www.theguardian.com/news/series/australia-v-the-climate).
> Add flex URL for podcast Australia v the climate

- cloudformation.yaml
- conf/riff-raff.yaml
- podcasts-rss.service
- Moves deployment to ARM from x86
- Updated base image, with Ubuntu 20.04 LTS and Corretto 11 JVM
Deploy it. Does it work?
Slightly reduced costs and slightly happier managers
This is a well-trodden path and it's expected that if it fails it will do so quickly by failing to start up. It hasn't so far.
> Ubuntu & ARM update

- .github/workflows/build.yml
- README.md
- app/AppComponents.scala
- app/com/gu/itunes/SecretKeeper.scala
- app/controllers/Application.scala
- build.sbt
- cdk/.gitignore
- cdk/README.md
- cdk/bin/cdk.ts
- cdk/cdk.json
- cdk/jest.setup.js
- cdk/lib/__snapshots__/podcasts-rss.test.ts.snap
- cdk/lib/podcasts-rss.test.ts
- cdk/lib/podcasts-rss.ts
- cdk/lib/policies.ts
- cdk/package-lock.json
- cdk/package.json
- cdk/tsconfig.json
- conf/application.conf
- conf/logback.xml
- conf/riff-raff.yaml
- project/plugins.sbt
- Switches the build system to Github Action
- Deprecates cloudformation.yaml in favour of CDK
- Updates to DEB artifact
- Ties it all together with Riffraff
- Reads CAPI key from Secrets Store (planning for auto-rotation)
- Reads Play! secrets from SSM
This is now live on PROD, with 50% traffic (at the time of writing).
If you run `curl -D- http://itunes-feed.content-aws.guardianapis.com/culture/series/university-of-cambridge-festival-of-ideas/podcast.xml`, you should get a podcast RSS.  Keep this up enough times and it should have been served by this update.
If you run `curl -D- https://itunes-feed.content-aws.guardianapis.com/culture/series/university-of-cambridge-festival-of-ideas/podcast.xml`, you should also get a podcast RSS which is always served by this update. (Route53 is smart …
> Implement CDK

- cdk/lib/podcasts-rss.ts
Changes DNS certification to podcast-feed..... instead of itunes-feed.…
**Before**
- If you run `curl https://itunes-feed.content-aws.guardianapis.com/news/series/the-audio-long-read/podcast.xml` you should get content.
- If you run `curl https://podcast-feed.content-aws.guardianapis.com/news/series/the-audio-long-read/podcast.xml` you should get a cert error (if you bypass with -k, you get the content again)
**After**
- If you run `curl https://itunes-feed.content-aws.guardianapis.com/news/series/the-audio-long-read/podcast.xml` you should get a cert error (if you bypass with -k, you get the content again)
- If you run `curl https://podcast-feed.content-aws.guardianapis.com/news/series/the-audio-long-read/podcast.xml` you should get content.
More inclusive (and accurate) naming
We have …
> Change certified domain name to podcasts-feed

- .github/workflows/build.yml
- app/com/gu/itunes/CustomCapiClient.scala
- app/com/gu/itunes/SecretKeeper.scala
- app/com/gu/itunes/iTunesRssItem.scala
- build.sbt
- cdk/package-lock.json
- cdk/package.json
- project/build.properties
- project/plugins.sbt
- test/com/gu/itunes/AcastProxySpec.scala
- test/com/gu/itunes/FilteringSpec.scala
- test/com/gu/itunes/ItunesRssFeedSpec.scala
- test/com/gu/itunes/ItunesRssItemSpec.scala
- test/com/gu/itunes/XmlTestUtils.scala
Big load of dependency upgrades, including:
- Scala 2.12 -> 2.13
- Play 2.6 -> 2.8
- CSC -> 19.x
- content-api-modes -> 17.5
- okhttp -> 4.10
- aws sdk -> 2.20.69
- netty-handler -> 4.1.94
- guava -> 32.0
This requires some minor code changes due to a deprecated feature in CSC and scala 2.13's treatment of mutable / immutable `Seq`
Deploy to CODE. Test that you still get the same results as you did before.
Everything generally just a bit more up-to-date
There are a lot of updates in here so we should be a bit careful and make sure we test properly
> Dependency upgrades

- build.sbt
- project/plugins.sbt
Updates some dependencies and adds an override for `netty-codec-http2`. It seems we can also do away with some of the other overrides we had in place - at least as far as local testing and running suggests.
Tested locally, all passed. Ran locally and compared the output for e.g. `news/series/the-audio-long-read/podcast.xml` side-by-side with PROD and it appeared to be identical.
If it builds and can be deployed successfully, we can test it further.
We should see no unusual behaviour or errors, and the output should be identical between versions.
There should be very little risk here, as long as locally observed behaviour persists all the way out to production.
N/A
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#scre …
> Bump some dependencies and remove unnecessary overrides

- build.sbt
- project/build.properties
- project/plugins.sbt
- bump logback for vulns
- simple-configuration-core as a patch was available
- SBT just because
Run it up, check it's working and logging
Fixes alerts
> Bump logback dependency

- app/com/gu/itunes/iTunesRssItem.scala
Requested by Gabriel Smith this morning:
> We have a new podcast, please can you add flex URLs and send the message to Acast to enable to new podcast series in the logs? 
> 
> Black Box
> https://www.theguardian.com/technology/series/blackbox
> https://www.theguardian.com/technology/series/blackbox/podcast.xml
First item in the podcast seems to have been posted yesterday based on [the podcast page](https://www.theguardian.com/technology/series/blackbox), so I’ve chosen yesterday as the date.
I think this is all that’s required, based on [the PR I found that Rowanne made last time](https://github.com/guardian/itunes-rss/pull/141), but I’ll have a look around for other changes around the same time.
> Add flex url for black box podcast

- app/com/gu/itunes/iTunesRssItem.scala
Requested by Mike Hohnen:
> Australia audio / CP have set up a new podcast series Who screwed millennials, and were wondering if you might be able to set up flex URLs? 
>
> Our audio team have the ability to ask Acast to enable the new series, so we can handle that step of the process, but please let me know if you'd prefer to handle it on your end. 
>
> https://www.theguardian.com/australia-news/series/who-screwed-millennials
> https://www.theguardian.com/australia-news/series/who-screwed-millennials/podcast.xml
Per @emdash-ie in https://github.com/guardian/itunes-rss/pull/151, I've used the [date of the first item](https://www.theguardian.com/australia-news/audio/2024/apr/11/introducing-who-screwed-millennials-podcast) as the date here, the 11th April 2024.
> Add 'who screwed millennials' tag to acastPodcasts

- app/com/gu/itunes/DateSupport.scala
- build.sbt
- project/plugins.sbt
Bumps as many dependency versions as we can currently get. Also removes a couple of `io.netty` overrides, so we'll see how that shapes up.
Run locally, check the output side-by-side with PROD. At first glance it looks identical.
If it doesn't break, I'll take that as a success, but will check for ongoing dependency issues anyway.
If it breaks, we redeploy the previous `main` build and then revert this PR or fix forwards, depending on the nature and severity of the failure.
**PROD (left) vs this branch (right):**
-   [ ] …
> Bump All The Things and see what happens

- README.md
- app/com/gu/itunes/SecretKeeper.scala
- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- app/controllers/Application.scala
- conf/application.conf
- test/com/gu/itunes/AcastProxySpec.scala
- test/com/gu/itunes/ItunesRssFeedSpec.scala
- test/com/gu/itunes/ItunesRssItemSpec.scala
- test/com/gu/itunes/ItunesTestData.scala
- test/resources/itunes-capi-comfort-eating-response.json
- test/resources/itunes-capi-full-story-response.json
For the ~AU full-story~ Grace Dent Comfort Eating podcast we want to use episodic artwork if possible. This tests the water in that area.
Locally you can export the necessary env vars (see the README) and run it. It'll generate the <itunes:image> elements for appropriate podcast's episodes only. The links won't actually work unless you export the correct salt. The salt also needs to be added to our configuration for access by `SecretKeeper`.
If we see per-episode images... success!
* Currently there are no coded protections against older series episodes - we may need a date-based gate to enable this in production.
* We exclude master assets from being considered for selection - this may or may not have to remain
* We don't specify an upper- or lower-bound size limit on the assets we do …
> Use fastly-resizer image URLs for specific podcast

- app/com/gu/itunes/SecretKeeper.scala
Fix for configuration snafu in https://github.com/guardian/itunes-rss/pull/157
We shouldn't use config file fastly salt value if empty in PROD as it stops us from getting the real value from secrets manager 🙄 
Tests still complete locally. Will need to check logs after deployment.
Before
`Loaded the fastly image resizer signature salt from configuration but it was an empty string`
Expected
`Loading <salt secret name> key from secrets manager at /<path-to-the-secret>`
Now that https://github.com/guardian/itunes-rss/pull/157 is in production, not fixing this in time will mean the launch episode of the new series is missed tomorrow.
N/A
-   [ ] [Navigable …
> Remove empty local config handler, should work same as apiKey

- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/itunes/ItunesRssItemSpec.scala
I got the format of the `<itunes:image>` tag wrong in https://github.com/guardian/itunes-rss/pull/157 - it should have had an `href=` string attribute instead of carrying the link to the image within the tag.
Have re-tested locally and updated the unit test so we can be pretty sure it's in the correct format now.
If we can see the artwork on the podcast - success!
Minimal risks here. The image is already in the feed and being ignored. Changing the format should make it work.
N/A
-   [ ] [Colour contrast …
> Add href attribute to episode image tag

- build.sbt
- project/plugins.sbt
Updates most dependencies
Local tests passed. Local side-by-side comparison with PROD looked identical.
Updated dependencies and operational service? Success!
There could be untested paths that haven't tickled the updated code. But this is always true - we'll rollback or fix forward depending on severity if we find anything like that.
N/A
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey …
> Bump most dependencies and override the heck out of jackson

- build.sbt
- test/resources/logback-test.xml
Here are a couple of small improvements to the test output when run locally: see the individual commit messages for more details.
This PR is inspired by the changes @fredex42 and I made to crier in https://github.com/guardian/crier/pull/174 (specifically commit https://github.com/guardian/crier/commit/59206fae5b65b5ece9b83df65f1b3bcba1637155).
> Improve test output locally

- app/com/gu/itunes/iTunesRssItem.scala
Adds the full story series tag and a start date of ~today (Monday October 7th)~ Tuesday October 8th for the first inclusion of the episodic artwork for that series.
Tested locally using Sunday October 6th as the activation date because Monday's edition wasn't available at the time.
Before:
```
<item>
<title>How England’s far-right riots erupted</title>
<itunes:title>How England’s far-right riots erupted</itunes:title>
<description>When racist chants rang out and homes, businesses and hotels housing asylum seekers were attacked, for a week in July and August English towns and cities seemed on the brink of chaos. This outbreak followed the deaths of three young children at a Taylor Swift-themed dance class. Josh Halliday reports on what we know so far about the people at the centre of the …
```
> Enable episodic artwork for Full Story podcast

- .github/workflows/build.yml
- .tool-versions
Makes the following changes in order to make sbt available:
- adds `setup-scala` to workflow
- creates `.tool-versions` to define the Java version
Workflow ran successfully on this branch
No more failing workflows
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Add setup-scala to workflow

- app/com/gu/itunes/iTunesRssItem.scala
We're setting up for a new tag created to help Australia resurface some past episodes but now with episodic artwork.
Once deployed we can query for the new tag and see the data that comes back. It may be largely empty until some episodes have been appropriately tagged.
If the "new" series has episodes with the new artwork, we're good.
This isn't breaking new ground so should be pretty risk-free. No platforms are currently aware of this new series so they won't come asking for it until we tell them about it anyway.
N/A
- …
> Add new guardian australia podcast series tag

- app/com/gu/itunes/Filtering.scala
- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/itunes/FilteringSpec.scala
We currently (and have [since PR #29 in 2016](https://github.com/guardian/itunes-rss/pull/29)) remove all HTML from RSS item description fields. But then we append the supporter revenue links back in again anyway and this doesn't appear to break Apple or Spotify podcasts even though it does break [feed validation](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.theguardian.com%2Fnews%2Fseries%2Ftodayinfocus%2Fpodcast.xml).
We recently received a request from editorial to re-enable these links, and as we're already breaking the validator but the links appear to work anyway, we figured we'd try it.
Have run it locally, here's a before and after
Demonstrating links:
```
Before:
<description>Helen Pidd and Alexandra Topping have been close friends for almost 20 years. But …
```
> Preserve links in rssItem descriptions

- app/com/gu/itunes/iTunesRssItem.scala
Gets us ready to start using auto-cropped episodic artwork for the Today in Focus series. We're waiting for the actual start date to be provided, so I set it to 100 years in the future for the moment. We ought to get there before then, but if we don't it won't be my problem 😆 
We have experience of other series that have followed this pattern before, so from a technical point of view this should be good to merge and go when the editorial templates are ready and the date is adjusted.
We should expect images to arrive per episode vey quickly on e.g. Spotify. Apple podcasts may take longer.
If it is activated too soon, we may generate substandard image crops. Not the end of the world, generally because most images crop quite well anyway, but we'd prefer not to be in that situation.
Not …
> Setup for TiF episodic artwork

- app/com/gu/itunes/Filtering.scala
- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/itunes/FilteringSpec.scala
Editorial frequently write specific links into the trail text of podcasts and wonder why this isn't reflected out on the podcast platforms. Typically this is because we explicitly remove html from there as it breaks some feed spec validation checks.
However, since #170 we have seen that some of these elements are at least rendered, so we're going to try the same thing for Politics Weekly America.
The difference with this particular series though is that in addition to links, `<br>` elements are used instead of straightforward punctuation, and we don't know how well or badly those will be received by the platforms. So we're going to start with the minimum possible impact and include episodes launched on or after April 4th 2025 as we know there is only one (at the time of creating this PR) …
> Allow html in description for US politics weekly from Apr 4 2025

- app/com/gu/itunes/iTunesRssItem.scala
Adds the blackbox series tag and a start date of today (Thursday 22nd May, 2025) for the first inclusion of the episodic artwork for that series.
I have attempted to test this by modifying the date to be in the past (`DateTime(2020, 5, 22, 0, 0)`), running the application locally and visiting:
http://localhost:9000/technology/series/blackbox/podcast.xml
~However, the expected images don't appear in the way Justin noted [here](https://github.com/guardian/itunes-rss/pull/164). I think this might be because I didn't run this beforehand, as per the [instructions](https://github.com/guardian/itunes-rss?tab=readme-ov-file#to-run-locally):~
```
export FASTLY_SALT=astringthatactuallyworkswillbeneeded
```
~Where do I get this salt from?~
UPDATE: we got this working by pulling the production salt …
> Enable episodic artwork for blackbox podcast

- cdk/bin/cdk.ts
- cdk/lib/__snapshots__/podcasts-rss.test.ts.snap
- cdk/lib/podcasts-rss.test.ts
- cdk/lib/podcasts-rss.ts
> [!NOTE]
> Easiest to review [commit by commit](https://github.com/guardian/itunes-rss/pull/181/commits).
This change enables access logging on the load balancer, shipping logs to the organisational S3 bucket which is queryable in Grafana. See also https://github.com/guardian/aws-account-setup/pull/352.
We want to understand which clients are accessing the load balancer. Searching the access logs enables us to gain this insight.
After [deploying `main` to CODE](https://riffraff.gutools.co.uk/deployment/view/b8cc0939-f4ca-4e1b-b94f-98e6ab993633)[^1], I've successfully [deployed this branch](https://riffraff.gutools.co.uk/deployment/view/e2b6fc4f-2f22-48ce-8322-3f2fb8b10a55). The access logs are now [queryable within Grafana](https://metrics.gutools.co.uk/goto/tgC9_SsHg?orgId=1).
Access …
> feat(cdk): Enable load balancer access logging 

- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- build.sbt
- test/com/gu/itunes/AcastProxySpec.scala
- test/com/gu/itunes/ItunesRssItemSpec.scala
- test/com/gu/itunes/ItunesTestData.scala
- test/resources/itunes-capi-no-episode-number.json
Pulls in the new fields from CAPI:
- `podcastEpisodeNumber` (optional) - the episode number of the podcast
- `podcastSeasonNumber`(optional) - the season number of the podcast
In order to more robustly model episode numbering for podcasts with type `serial`.
This will supersede our current approach which relies on episode numbering information being present in the `webTitle` field: https://github.com/guardian/itunes-rss/pull/153.
Furthermore, pulls in the new field:
- `podcastEpisodeType` (optional) - the episode type of the podcast. Can be one of full, trailer or bonus. If absent, we assume it's a full episode
Unit tests should pass.
Hard to test beyond that until we have production data coming through with the new fields set.
All podcasts of type `serial` can have their episode and …
> Use new episode numbering and type fields from CAPI
