guardian/itunes-rss

- app/com/gu/itunes/iTunesRssItem.scala
- conf/application.conf
- project/Build.scala
* Bump Scala Client version to 7.9
* Fix `pubdate` format 
* Add `explicit` and `clean` field
> Fix pubdate format and add explicit field

- app/controllers/Application.scala
> Back to 100!

- app/com/gu/itunes/CustomCapiClient.scala
- app/com/gu/itunes/iTunesRssFeed.scala
- project/Build.scala
- project/build.properties
- test/com/gu/ItunesRssFeedSpec.scala
- test/com/gu/ItunesRssItemSpec.scala
- test/com/gu/ItunesTestData.scala
- test/resources/itunes-capi-response.json
* support [itunes categories](https://help.apple.com/itc/podcasts_connect/#/itcb54353390)
* use `thrift`
*  update `scala` and `sbt`
> Support categories

- app/com/gu/itunes/CustomCapiClient.scala
- app/com/gu/itunes/iTunesRssFeed.scala
- test/com/gu/ItunesRssFeedSpec.scala
- do not use thrift until concierge has been updated
- fix serialisation and associated test
> Fix categories serialization

- app/com/gu/itunes/Filtering.scala
- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- project/Build.scala
- test/com/gu/FilteringSpec.scala
- test/com/gu/ItunesRssFeedSpec.scala
- test/resources/itunes-capi-response.json
Improve our [feed validation compliance](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.theguardian.com%2Fcommentisfree%2Fseries%2Fwhat-would-a-feminist-do%2Fpodcast.xml) by removing html (`a`, `p, `b`, `br`)
> Remove html 

- app/com/gu/itunes/iTunesRssItem.scala
This is a test run by membership
> Add a membership CTA for politics weekly new podcasts

- app/com/gu/itunes/iTunesRssItem.scala
> use acast proxy for trial podcast

- podcasts-rss.service
The process is using too much memory for t2.micro, it keeps being terminated.
I've had this branch running in PROD for a couple of days and seems fine
> Lower max memory

- app/com/gu/itunes/iTunesRssItem.scala
Followind demand from central production
> Use trail field if standfirst field is not defined

- app/com/gu/itunes/CustomCapiClient.scala
- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- project/Build.scala
- test/com/gu/ItunesRssFeedSpec.scala
- test/com/gu/ItunesTestData.scala
- test/resources/itunes-capi-response.json
> Add podcast type

- cloudformation.yaml
- conf/riff-raff.yaml
The deploy has been broken for a while.
Also switched to xenial and added ssm
> Fix s3 download

- cloudformation.yaml
t2.micro does not have enough memory
(this could probably be a lambda instead of a play app)
> Use t3.small

- app/com/gu/itunes/iTunesRssItem.scala
> Changes the author for items of "The Token"

- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- test/com/gu/AcastProxySpec.scala
- test/com/gu/ItunesRssItemSpec.scala
The author fields at the channel and items level now match.
> Apply author for the token everywhere

- app/com/gu/itunes/iTunesRssItem.scala
- conf/application.conf
Setup the Flex/Acast URLs for the new "Look at me" podcast.
> Add "Look at me" podcast

- app/com/gu/itunes/iTunesRssItem.scala
This will make every episode of the new Spin podcast downloaded via Acast.
> Add new spin podcast

- app/com/gu/itunes/iTunesRssItem.scala
Haven't added any specific tests for this yet - waiting to see if it goes green as-is 🤞
> Add new AU "full story" podcast

- app/com/gu/itunes/iTunesRssItem.scala
I think this is the only change needed here. Just waiting for clarification of what 'add the flex tags' means when CP ask.
> Add Gene Gap Acast launch group

- app/com/gu/itunes/iTunesRssItem.scala
Adds a tag in preparation for Acast setting up the new podcast.
> Add forgotten stories of football Acast group

- app/com/gu/itunes/iTunesRssItem.scala
Adds a tag in preparation for Acast setting up the new podcast.
> Add Innermost Acast Group

- app/com/gu/itunes/iTunesRssItem.scala
> Add australia-news/series/temporary AcastLaunchGroup

- app/com/gu/itunes/iTunesRssItem.scala
This PR adds a AcastLaunchGroup for "music/series/reverberate" as requested by Patrick Lum via email.
> Add music/series/reverberate AcastLaunchGroup

- README.md
Just a new joiner writing down their understanding of what this service does.
No code changes.
> Document the method of operation; queries CAPI by tag id

- app/com/gu/itunes/iTunesRssItem.scala
> Clean up; remove gaps in title and description tags.

- app/com/gu/itunes/iTunesRssItem.scala
As the title states - following this documentation: https://docs.google.com/document/d/1UJ_-fonY2YcBLgex5R7It-avPMYZZ3FtFHIOhVep8i4/edit#
> Add acast tags for Saved For Later podcast series

- project/build.properties
Bumps sbt to 1.5.7
Compiled and successfully published locally.
Working in prod as before
Low-risk change
> Bump sbt version to 1.5.7

- app/com/gu/itunes/iTunesRssFeed.scala
This limits the number of podcasts published before 24th December in a feed to 100.
Before 24th December 2021 the podcasts feed had 200 items, but with items 100-200 repeated so it looked like 300 items. Apple seems to have mostly ignored items >100 in the feed, presumably because of how they handle duplicates.
On 24th December 2021 we fixed the bug so that the feed had 300 unique items. Apple downloads of any items that were brought back into the feed by this change increased massively.  They have since reduced but not to the level we would expect.  The appleExcessDownloadsWorkaround is intended to allow us to gradually increase the number of podcasts in the feed to 300, without having to bring old items back into the feed.
We should be able to remove this workaround at some point in the …
> Workaround for Apple download strange behaviour

- app/com/gu/itunes/iTunesRssItem.scala
Co-authored-by: Divya Bhatt <divya.bhatt@guardian.co.uk>
This adds the Acast flex tags for the new podcast "Can I tell you a secret?"
> Add new "Can I tell you a secret?" podcast tags

- app/com/gu/itunes/iTunesRssItem.scala
This adds the Acast flex url for the new podcast "An impossible choice"
> Add flex url for an impossible choice podcast

- app/com/gu/itunes/CustomCapiClient.scala
- app/com/gu/itunes/Filtering.scala
- app/com/gu/itunes/iTunesRssFeed.scala
- app/com/gu/itunes/iTunesRssItem.scala
- app/controllers/Application.scala
- build.sbt
- test/com/gu/itunes/FilteringSpec.scala
- test/com/gu/itunes/ItunesRssItemSpec.scala
This is lowering down High snyk vulnerabilities from 6 to 0.
And total vulnerabilities (high/medium/low) from 75 to 10.
Jsoup Library (one of direct dependency) also rectified to latest version and with relative changes in the code by @fredex42.
Before: 
After 1st iteration: 
After 2nd iteration:
regarding Jsoup library:
By running at localhost as mentioned in Readme and trying to load any RSS feed.
(While doing this PR, each library change has been tested via `sbt test` and `sbt run` and fetching podcast RSS feed successfully.)
Server should run fine with no library errors/exceptions on console.
Shouldn't be case as we are doing this to making it highly secure
> Lowering snyk high from 6 to 0 and overall vulns from 75 to 10.

- app/com/gu/itunes/iTunesRssItem.scala
Support new Cotton Capital podcast.
> Add Cotton Capital flex url
